apiVersion: v1
kind: Service
metadata:
  name: restful-service
  labels:
    tier: pod-ip-service
spec:
  selector:
    pods: restful-pods
  ports:
    - port: 3000
      protocol: "TCP"
      targetPort: 3000
  type: LoadBalancer
