POST http://localhost:3000/favorites
Content-Type: application/json

{
    "type":"movie",
    "name":"The Empire Strikes Back",
    "url":"https://swapi.dev/api/films/2/"
}

###
POST http://localhost:3000/favorites
Content-Type: application/json

{
    "type":"character",
    "name":"Luke Skywalker",
    "url": "https://swapi.dev/api/people/1/"
}

###
GET http://localhost:3002/favorites