version: "3.8"
volumes:
  data:
  logs:
# networks:
#   goals-net:
#     driver: bridge

services:
  mongoserver:
    image: "mongo"
    volumes:
      - data:/data/db
    # env_file:
    #   - ./env/mongo.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  goals-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env
    environment:
      - DNSNAME=mongoserver
    volumes:
      - logs:/app/logs
      - /app/node_modules
      # - ./backend:/app
    ports:
      - "8085:8085"
    depends_on:
      - mongoserver
  goals-frontend:
    # build: /frontend/Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - mongoserver
      - goals-backend
